module.exports = {
  apps: [
    {
      name: '99group-games-nextjs',
      script: 'npx',
      args: 'next start',
      cwd: '/home/ubuntu/game-platform01/nextjs-game-platform',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOSTNAME: '0.0.0.0',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOSTNAME: '0.0.0.0',
      },
      error_file: '/home/ubuntu/logs/99group-games-nextjs-error.log',
      out_file: '/home/ubuntu/logs/99group-games-nextjs-out.log',
      log_file: '/home/ubuntu/logs/99group-games-nextjs-combined.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: '99group-backend',
      script: 'server_enhanced.js',
      cwd: '/home/ubuntu/game-platform01/nextjs-game-platform',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3068,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3068,
      },
      error_file: '/home/ubuntu/logs/99group-backend-error.log',
      out_file: '/home/ubuntu/logs/99group-backend-out.log',
      log_file: '/home/ubuntu/logs/99group-backend-combined.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
}
