module.exports = {
  apps: [
    {
      name: 'fun88-backend',
      script: 'server_enhanced.js',
      cwd: '/home/ubuntu/fun88-v1',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
        PUBLIC_DOMAIN: 'http://localhost:5000',
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3006,
        PUBLIC_DOMAIN: 'http://localhost:5000',
      },
      log_file: './logs/backend-combined.log',
      out_file: './logs/backend-out.log',
      error_file: './logs/backend-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'uploads', '.next'],
      watch_options: {
        followSymlinks: false,
      },
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'fun88-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/home/ubuntu/fun88-v1',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        NEXT_PUBLIC_API_URL: 'http://localhost:3006',
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 5000,
        NEXT_PUBLIC_API_URL: 'http://localhost:3006',
      },
      log_file: './logs/frontend-combined.log',
      out_file: './logs/frontend-out.log',
      error_file: './logs/frontend-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'uploads', '.next'],
      watch_options: {
        followSymlinks: false,
      },
    },
  ],
}
